---
server:
  port: 9090
spring:
  main:
    web-application-type: reactive
  application:
    name: ticketplus-gateway
  cloud:
    gateway:
      routes:
        - id: ticketplus-service
          uri: lb://ticketplus-service
          predicates:
            - Path=/vehicles/**,/users/**,/ticket/**,/passenger/**,/locations/**,/expeditions/**,/confirmations/**
        - id: ticketplus-payment-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/payments**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/